### ISSUE TITLE
Index 0 out of bounds for length 0 error

### ISSUE THREAD

**Issue by Mengflz** [icbi-lab/luca#13]
Dear authors,
Thank you very much for your work. I am new to nextflow. After I download related and follow the command you give 
"nextflow run main.nf --workflow downstream_analyses -resume -profile icbi_lung  --build_atlas_dir ./data/20_build_atlas  --outdir ./data/30_downstream_analyses"
![WX20231013-122501@2x](https://github.com/icbi-lab/luca/assets/51097823/b02e2945-2d1a-4bea-8196-3c7c62c241cc)

This error always occurs. I run this on a server instead of HPC. I don't know why this error occurred. Is it related to the environment I am using?

Here is the error info from log file:
<img width="1440" alt="image" src="https://github.com/icbi-lab/luca/assets/51097823/f646ac54-c3c8-4df7-afaf-98c91bd0d0b2">

**Comment by grst** [comment]
I believe I have seen this before and it was related to a newer nextflow version that is incompatible with this workflow for whatever reason. 

Could you try to run 
```
export NXF_VER=22.04.5
```
before `nextflow run ...`? 

If this works, I'll update the README accordingly.

**Comment by Mengflz** [comment]
Sorry for my delayed response. It works. Thank you very much!

But I met a different problem after I fix this. The apptainer/Singularity shows they lack the permission of namespace. I have installed it with suid and run it as root. I've searched for relevant information , but it is very limited and I can't resolve the issue.
