### ISSUE TITLE
Epithelial Cell Types

### ISSUE THREAD

**Issue by c-westhoven** [icbi-lab/luca#14]
Hi!

We were wondering what happened to the different epithelial cell types in [33_epithelial_cells
](https://github.com/icbi-lab/luca/blob/master/analyses/30_annotate_scrnaseq_data/33_epithelial_cells.py)
In our project, we are interested in epithelial cells (Goblet cells in particular). Were these cell types filtered out during preprocessing or not found at all?

In the script 33_epithelial_cells.py Goblet cells are mentioned, but the plots aren't visible to give more context. 

Thanks in advance!

**Comment by grst** [comment]
Hi Charlotte, 

there's no reason to expect that goblet cells would be absent. However, t=given the markers I had at hand when I was annotating the cell types I wasn't able to clearly distinguish them form other epithelial subtypes. 

One reason for this could be "over-integration" -- Integrating data from different experimental platforms made the integration task pretty hard for scvi-tools and probably led to a reduced resolution. But maybe I just didn't use the right markers and you can find them if you take a look at the epithelial cells yourself. 

Cheers, 
Gregor
