### ISSUE TITLE
malignant cells labeled in normal samples

### ISSUE THREAD

**Issue by rpeys** [icbi-lab/luca#17]
Hi,

I downloaded the extended data atlas from CellxGene, and was surprised to find many cells labeled as "malignant" in supposedly normal tissues (see screenshot containing malignant cell counts per disease/study/origin below - data was aggregated from the cell metadata in the downloaded h5ad file). Can you please help me understand how these cell type labels were generated, and explain the presence of these malignant labels in normal tissues? I thought perhaps it was due to mislabeling during transfer learning, but many of these cells come from the core atlas datasets.

Thanks,
Rebecca

<img width="698" alt="image" src="https://github.com/icbi-lab/luca/assets/19732554/ad641e5d-f12e-4bcb-8fc1-04cae981b220">

**Comment by grst** [comment]
Hi @rpeys, 

there are two factors that likely play a role her: 
 * samples labelled as `normal_adjacent` might still contain a small number of tumor cells as the labelling by the pathologist might be imperfect
 * the tumor cells were assigned based on unsupervised clustering. If you look at the UMAP of the epithelial cluster, you can see that there are no perfect boundaries between healthy and malignant cells, leading to some healthy cells being in the cluster that we assigned to tumor cells. This can be on the one hand a result of "over-integration" by scvi-tools, on the other hand it can be that some tumor are transcriptionally very similar to normal epithelial cells (and we would need information about their morphology and mutations to clearly separate them).

**Comment by rpeys** [comment]
Got it, thanks for shedding light!
