### ISSUE TITLE
Loading the h5ad

### ISSUE THREAD

**Issue by linqiaozhi** [icbi-lab/luca#3]
Congratulations on a very nice preprint.

I am trying to load the extended atlas from the .h5ad provided. In R, using loomR's connect() function I encounter the following error:

```R
lfile  <- connect( filename = 'data/extended_atlas.h5ad' )
Error in validateLoom(object = self) :
  There can only be one dataset at the root of the loom file
```

When I tried using python:
```python
out.file =  scanpy.read_10x_h5 ('data/extended_atlas.h5ad')
ValueError: 'data/extended_atlas.h5ad' contains more than one genome. For legacy 10x h5 files you must specify the genome if more than one is present. Available genomes are: ['X', 'obs', 'obsm', 'obsp', 'raw', 'uns', 'var']
```

So I then attempted using the raw "genome," and encountered this error:
```python
Exception: File is missing one or more required datasets.
```

I work mostly in R for scRNA-seq analyses, so I don't have much experience with the h5ad format. How can I go about loading this file?

**Comment by grst** [comment]
Hi @linqiaozhi, 

you'll need `sc.read_h5ad`. 
The function you are using is for files generated by 10x Genomics Cellranger. 

If you need help getting started with scanpy, I recommend checking out the [scverse tutorial page](https://scverse.org/learn/) and the [scverse community forum](https://discourse.scverse.org/). I'm also around there. 

Best, 
Gregor

**Comment by linqiaozhi** [comment]
Thanks Gregor--that was clearly the problem.
