### ISSUE TITLE
Question about cluster idents in Seurat object

### ISSUE THREAD

**Issue by ssun1116** [icbi-lab/luca#7]
Hello authors. Thanks for sharing the valuable data and code.
While reproducing the data analysis using Seurat, I had a question about the differences between three idents that can be used to annotate the clusters: `cell_type`, `cell_type_major`, and `cell_type_tumor`.
Sometimes, the same cluster is named differently depending on which ident we used for annotating the cluster.
For example, a cluster annotated with "type I/II pneumocytes" with `cell_type` ident is differently annotated with "Alveolar cell type 1/2" when using the `cell_type_major` ident. 
Could you explain the differences between these three idents, and what should I use as the principal object for the annotation?
Thank you so much.

**Comment by grst** [comment]
Hi @ssun1116, 

thanks for your question! 
Assuming you downloaded the dataset from cell-x-gene: 

 * `cell_type` contains standardized cell-type annotations as defined by the cell-ontology. This is one of the fields controlled by cell-x-gene, and in general, I'd recommend to use this annotation unless you need a higher resolution or want to reproduce results from our paper. 

The other cell-type annotations are provided by us and the labels just are those that we used for the paper:
 * `cell_type_tumor` is the most fine-grained resolution (higher resolution for than `cell_type`, as we could not map all labels to the cell ontology)
 * `cell_type_neutro(_coarse)` is the same as `cell_type_tumor`, but additionally contains the neutrophil cluster labels
 *  `cell_type_major` is a medium-resolution annotation that we used for most analyses in the paper. 

Hope that helps,

**Comment by ssun1116** [comment]
Got it. Thank you for the clarification!
