### ISSUE TITLE
Is there rds/Seurat data can be downloaded for extended and Core atlas with the mutation information of STK11?

### ISSUE THREAD

**Issue by shawnql08** [icbi-lab/luca#8]
Hi, I am not a professional bioinformatics person. I am interested in the data with or without STK11 mutations. Could you please let me know which dataset that I can download? It would be great if the dataset include the mutations information of STK11 as well as other key oncogenes mentioned in the paper? I can only start with RDS or Seurat data. Could you please send me the direct link to download the data?

I sincerely appreciate your help.

Regards,
Shawn

**Comment by grst** [comment]
Hi @shawnql08, 

I'm afraid there is no mutation data for the single-cell datasets (to my knowledge, the only dataset in our atlas with genotypic information is from Maynard et al.). 

In our paper, we integrated bulk RNA-seq data from TCGA which has mutation data with the single cell data using [scissor](https://github.com/sunduanchen/Scissor) to associate cells with mutations.
