### ISSUE TITLE
Modules  scanpy_helpers / AnnotationHelper

### ISSUE THREAD

**Issue by bangbattlers** [icbi-lab/luca#9]
Hi,

I love to explore these thrilling datasets and code, but I've got one error I want to ask.

From the code at analyses/37_subclustering/37_neutrophil_subclustering.py
I tried to import following modules and functions

"from scanpy_helpers.annotation import AnnotationHelper
import scanpy_helpers as sh"

, but I countered the errors that there is no module scanpy_helpers neither AnnotationHelper.

From Googling, I seems there are no module called scanpy_helpers neither AnnotationHelper that I can install.
How could I use the modules ? Is there any specific routes that I can install these?

Thanks
bangbattlers

**Comment by grst** [comment]
Hi, 

the package is in this repo in the `lib` subfolder. It's not an official package but rather a bunch of customized code for this project. 

You can install it like this:
```bash
git clone https://github.com/icbi-lab/luca.git
cd luca/lib
pip install -e ./scanpy_helper_submodule
```
